namespace PDV.Api.DTOs;

public sealed record TransportadoraRequest(
    string Nome,
    string? NomeFantasia,
    string? Documento,
    string? InscricaoEstadual,
    string? Telefone,
    string? Email,
    string? Responsavel,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Uf,
    string? CodigoMunicipioIbge,
    string? Endereco,
    string? CorTemaHex,
    int? PrazoMedioEntregaMinutos,
    string? Observacao,
    bool Ativo);

public sealed record TransportadoraDto(
    Guid TransportadoraId,
    Guid EmpresaId,
    string Nome,
    string? NomeFantasia,
    string? Documento,
    string? InscricaoEstadual,
    string? Telefone,
    string? Email,
    string? Responsavel,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Uf,
    string? CodigoMunicipioIbge,
    string? Endereco,
    string? CorTemaHex,
    int? PrazoMedioEntregaMinutos,
    string? Observacao,
    bool Ativo,
    DateTime DataCadastro);
