namespace PDV.Api.DTOs;

public sealed record EmpresaFiscalDto(
    Guid EmpresaId,
    string Nome,
    string? NomeFantasia,
    string? Cnpj,
    string? InscricaoEstadual,
    bool InscricaoEstadualIsento,
    string? InscricaoMunicipal,
    string? CnaePrincipal,
    string? Telefone,
    string? EmailFiscal,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Uf,
    string? CodigoMunicipioIbge,
    string? CertificadoDigitalCaminho,
    bool CertificadoDigitalConfigurado,
    DateTime? CertificadoDigitalValidoAte,
    string? CertificadoDigitalErroValidacao,
    string RegimeTributario,
    string AmbienteNfe,
    string ProviderFiscal,
    bool UsaIntegracaoDiretaSefaz,
    string? ApiFiscalClientId,
    bool ApiFiscalClientSecretConfigurado,
    string? UrlApiFiscal,
    bool TokenApiFiscalConfigurado,
    string CobrancaDigitalProvider,
    string AmbienteCobrancaDigital,
    string? ApiCobrancaClientId,
    bool ApiCobrancaClientSecretConfigurado,
    string? UrlApiCobranca,
    int DiasVencimentoCobranca,
    bool CobrancaDigitalPronta,
    IReadOnlyCollection<string> CobrancaDigitalPendencias,
    int SerieNfe,
    int ProximoNumeroNfe,
    bool ProntaParaNfe,
    IReadOnlyCollection<string> PendenciasEmissao);

public sealed record EmpresaFiscalCertificadoUploadDto(
    string Caminho,
    string NomeArquivo,
    long TamanhoBytes);

public sealed record EmpresaFiscalCertificadoTesteRequest(
    string? Caminho,
    string? Senha);

public sealed record EmpresaFiscalCertificadoTesteDto(
    bool Valido,
    string Mensagem,
    string? Caminho,
    DateTime? ValidoAte,
    bool ProvavelmenteCompativelIcpBrasilA1,
    bool CertificadoDesenvolvimento,
    string? CnpjCertificado,
    bool? CnpjConfereComEmpresa,
    string? DiagnosticoCompatibilidade);

public sealed record EmpresaFiscalSefazDiagnosticoDto(
    string Etapa,
    string Resumo,
    string? CausaProvavel,
    bool TlsHandshakeSucesso,
    string? TlsProtocol,
    string? CipherSuite,
    int? HttpStatusCode,
    bool RespostaHtml,
    string? CertificadoServidorAssunto,
    string? CertificadoServidorEmissor,
    string? CertificadoServidorThumbprint,
    DateTime? CertificadoServidorValidoAte,
    string? ErrosCertificadoServidor,
    string? CertificadoClienteAssunto,
    string? CertificadoClienteThumbprint,
    DateTime? CertificadoClienteValidoAte,
    string? UsuarioExecucaoWindows,
    string? ModoArmazenamentoChave,
    string? DetalheTecnico);

public sealed record EmpresaFiscalSefazStatusDto(
    bool Disponivel,
    int? CodigoStatus,
    string Mensagem,
    string ProviderFiscal,
    bool UsaIntegracaoDiretaSefaz,
    string Ambiente,
    string Uf,
    string Url,
    DateTime? DataRecebimento,
    DateTime ConsultadoEmUtc,
    EmpresaFiscalSefazDiagnosticoDto? Diagnostico);

public sealed record EmpresaFiscalRequest(
    string Nome,
    string? NomeFantasia,
    string? Cnpj,
    string? InscricaoEstadual,
    bool InscricaoEstadualIsento,
    string? InscricaoMunicipal,
    string? CnaePrincipal,
    string? Telefone,
    string? EmailFiscal,
    string? Cep,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Uf,
    string? CodigoMunicipioIbge,
    string? CertificadoDigitalCaminho,
    string? SenhaCertificadoDigital,
    string RegimeTributario,
    string AmbienteNfe,
    string ProviderFiscal,
    bool UsaIntegracaoDiretaSefaz,
    string? ApiFiscalClientId,
    string? ApiFiscalClientSecret,
    string? UrlApiFiscal,
    string? TokenApiFiscal,
    string CobrancaDigitalProvider,
    string AmbienteCobrancaDigital,
    string? ApiCobrancaClientId,
    string? ApiCobrancaClientSecret,
    string? UrlApiCobranca,
    int DiasVencimentoCobranca,
    int SerieNfe,
    int ProximoNumeroNfe);
