<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseAppHost>true</UseAppHost>
    <AssemblyName>PDV.Launcher</AssemblyName>
    <RootNamespace>PDV.Launcher</RootNamespace>
    <Company>Samuel</Company>
    <Product>PDV Control Hub</Product>
    <Version>0.1.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

</Project>
